name: lsst
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=7_kmp_llvm
  - ads=0.12.7=pyhd8ed1ab_0
  - affine=2.4.0=pyhd8ed1ab_1
  - aom=3.12.1=h7934f7d_0
  - arrow-cpp=21.0.0=hb2ad71a_2
  - asdf=5.1.0=pyhd8ed1ab_0
  - asdf-astropy=0.9.0=pyhd8ed1ab_0
  - asdf-coordinates-schemas=0.4.0=pyhd8ed1ab_0
  - asdf-standard=1.4.0=pyhd8ed1ab_0
  - asdf-transform-schemas=0.6.0=pyhd8ed1ab_0
  - asdf-wcs-schemas=0.5.0=pyhd8ed1ab_0
  - astropy=7.1.1=py314hc849d88_0
  - astropy-base=7.2.0=py314hc02f841_0
  - astropy-iers-data=0.2025.12.8.0.38.44=py314h06a4308_0
  - astroquery=0.4.11=pyhd8ed1ab_0
  - attrs=25.4.0=pyhcf101f3_1
  - aws-c-auth=0.9.0=hb25bd0a_2
  - aws-c-cal=0.9.2=h3ff94e8_1
  - aws-c-common=0.12.4=hb25bd0a_0
  - aws-c-compression=0.3.1=hb25bd0a_2
  - aws-c-event-stream=0.5.6=hb25bd0a_0
  - aws-c-http=0.10.4=hb25bd0a_0
  - aws-c-io=0.21.4=h3eb0749_0
  - aws-c-mqtt=0.13.3=hb25bd0a_0
  - aws-c-s3=0.8.7=h3ff94e8_0
  - aws-c-sdkutils=0.2.4=hb25bd0a_1
  - aws-checksums=0.2.7=hb25bd0a_1
  - aws-crt-cpp=0.34.0=h7934f7d_0
  - aws-sdk-cpp=1.11.638=hac3f51a_0
  - backports=1.0=pyhd8ed1ab_5
  - backports.tarfile=1.2.0=pyhcf101f3_2
  - backports.zstd=1.3.0=py314h680f03e_0
  - beautifulsoup4=4.14.3=pyha770c72_0
  - blas=1.0=mkl
  - blosc=1.21.6=hef167b5_0
  - bottleneck=1.4.2=py314h6a40391_1
  - brotli-python=1.2.0=py314h3dd09e2_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=2.0.0=py314h4eded50_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyh8f84b5b_1
  - click-plugins=1.1.1.2=pyhd8ed1ab_0
  - cligj=0.7.2=pyhd8ed1ab_2
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.3=py314hdb19cb5_0
  - cryptography=46.0.3=py314h7fe84b3_1
  - cspice=67=hb03c661_12
  - cycler=0.12.1=py314h06a4308_0
  - cyrus-sasl=2.1.28=h1110e0f_3
  - dav1d=1.2.1=h5eee18b_0
  - dbus=1.16.2=h3c4dab8_0
  - dnspython=2.8.0=pyhcf101f3_0
  - expat=2.7.3=h7354ed3_4
  - fontconfig=2.15.0=h2c49b7f_0
  - fonttools=4.60.1=py314hee96239_0
  - freetype=2.13.3=h4a9f257_0
  - freexl=2.0.0=hf309648_0
  - fribidi=1.0.10=h7b6447c_0
  - geos=3.10.6=h9db6f96_0
  - geotiff=1.7.0=ha59944b_4
  - gettext=0.21.0=hedfda30_2
  - gflags=2.2.2=h6a678d5_1
  - giflib=5.2.2=hd590300_0
  - ginga=5.5.1=pyhd8ed1ab_1
  - glog=0.5.0=h6a678d5_1
  - graphite2=1.3.14=h295c915_1
  - gwcs=0.26.1=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=10.2.0=hdfddeaa_1
  - hpack=4.1.0=pyhd8ed1ab_0
  - html5lib=1.1=pyhd8ed1ab_2
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.1=h6a678d5_0
  - idna=3.11=pyhd8ed1ab_0
  - imageio=2.37.0=pyhfb79c49_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - jansson=2.14=h5eee18b_1
  - jaraco.classes=3.4.0=pyhcf101f3_3
  - jaraco.context=6.0.2=pyhcf101f3_1
  - jaraco.functools=4.4.0=pyhcf101f3_1
  - jeepney=0.9.0=pyhd8ed1ab_0
  - jmespath=1.0.1=pyhd8ed1ab_1
  - jpeg=9f=h5ce9db8_0
  - json-c=0.18=h6688a6e_0
  - keyring=25.7.0=pyha804496_0
  - kiwisolver=1.4.9=py314h24d9097_0
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lcms2=2.17=heab6991_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250814.1=cxx17_h7c8e02e_0
  - libarchive=3.8.2=h3ec8f01_0
  - libavif=1.3.0=h3539ee5_0
  - libblas=3.9.0=26_linux64_mkl
  - libbrotlicommon=1.2.0=h32cd6e7_0
  - libbrotlidec=1.2.0=ha2c5f68_0
  - libbrotlienc=1.2.0=h2e96acb_0
  - libcblas=3.9.0=26_linux64_mkl
  - libcups=2.4.15=hbe4054b_0
  - libcurl=8.17.0=hc93bc37_0
  - libdeflate=1.22=h5eee18b_0
  - libdrm=2.4.124=h5eee18b_0
  - libegl=1.7.0=h5eee18b_2
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgdal-core=3.11.4=hc92985d_0
  - libgfortran=15.2.0=h166f726_7
  - libgfortran5=15.2.0=hc633d37_7
  - libgl=1.7.0=h5eee18b_2
  - libglib=2.84.4=h77a78f3_0
  - libglvnd=1.7.0=h5eee18b_2
  - libglx=1.7.0=h5eee18b_2
  - libgomp=15.2.0=h4751f2c_7
  - libgrpc=1.74.1=ha2a6211_0
  - libhwloc=2.12.1=default_hf1bbc79_1000
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.8=hf80d704_0
  - libkml=1.3.0=haa4a5bd_1022
  - libkrb5=1.21.3=h520c7b4_4
  - liblapack=3.9.0=26_linux64_mkl
  - libllvm15=15.0.7=he89c38a_4
  - libmpdec=4.0.0=h5eee18b_0
  - libnghttp2=1.67.1=h697f920_0
  - libopengl=1.7.0=h5eee18b_2
  - libopenjpeg=2.5.4=hee96239_1
  - libpciaccess=0.18=h5eee18b_0
  - libpng=1.6.50=h2ed474d_0
  - libpq=17.6=ha51bf15_0
  - libprotobuf=6.33.0=h26c60c0_0
  - libre2-11=2025.11.05=h3218f0b_0
  - libsodium=1.0.20=heac8642_0
  - libspatialite=5.1.0=h798b768_2
  - libsqlite=3.51.1=h0c1763c_1
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libthrift=0.22.0=hd8eb582_0
  - libtiff=4.7.1=h029b1ac_0
  - libunistring=1.3=hb25bd0a_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.6.0=hb7bb969_0
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - llvm-openmp=20.1.8=h4922eb0_0
  - lmdb=0.9.31=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.3=pyh7db6752_0
  - matplotlib=3.10.7=py314h06a4308_0
  - matplotlib-base=3.10.7=py314h54cb298_0
  - mesalib=25.1.5=h31e3550_0
  - minizip=4.0.3=hf59b114_0
  - mkl=2024.2.2=ha770c72_17
  - mkl-service=2.5.2=py314hd44daad_1
  - mkl_fft=2.0.0=py314h744ab3d_1
  - mock=5.2.0=pyhd8ed1ab_0
  - more-itertools=10.8.0=pyhcf101f3_1
  - mysql-common=9.3.0=h9e076cb_4
  - mysql-libs=9.3.0=h6ecde68_4
  - ncurses=6.5=h7934f7d_0
  - networkx=3.6.1=pyhcf101f3_0
  - numexpr=2.14.1=mkl_py314h447c14d_1
  - numpy=2.4.0=py314h2b28147_0
  - openldap=2.6.10=he9288cc_1
  - openorb=1.3.0=np2py314ha313a2c_1
  - openorb-data=1.0.1.20181028=0
  - openorb-data-de430=1.0=0
  - openssl=3.6.0=h26f9b46_0
  - orc=2.2.0=h13e6d3f_1
  - packaging=25.0=py314h06a4308_1
  - pandas=2.3.3=py314hda4e5d8_1
  - pcre2=10.46=hf426167_0
  - photutils=2.3.0=py314hc02f841_1
  - pillow=12.0.0=py314h3b88751_1
  - pip=25.3=pyh0d26453_0
  - pixman=0.46.4=h7934f7d_0
  - proj=9.3.1=h1d62c97_0
  - pthread-stubs=0.3=h0ce48e5_1
  - puremagic=1.30=pyhe01879c_0
  - pyarrow=21.0.0=py314h973aee8_1
  - pycparser=2.22=pyh29332c3_1
  - pyerfa=2.0.1.5=py314hfdf79b4_1
  - pymongo=4.15.5=py314ha160325_0
  - pyparsing=3.2.5=py314h06a4308_0
  - pyqt=6.9.1=py314h43fb04a_0
  - pyqt6-sip=13.10.2=py314hee96239_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.14.2=h90eec9f_101_cp314
  - python-dateutil=2.9.0post0=py314h06a4308_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.14=2_cp314
  - pytz=2025.2=py314h06a4308_0
  - pyvo=1.8=pyhd8ed1ab_0
  - pyyaml=6.0.3=py314h591646f_0
  - qtbase=6.9.2=hd13baf8_5
  - qtdeclarative=6.9.2=h55666de_1
  - qtpy=2.4.3=pyhd8ed1ab_1
  - qtsvg=6.9.2=h75a08ff_1
  - qttools=6.9.2=hc856bc8_1
  - qtwayland=6.9.2=h9f1b7ec_1
  - qtwebchannel=6.9.2=hbdd6827_1
  - qtwebsockets=6.9.2=hbdd6827_1
  - rasterio=1.4.4=py314h584ab63_0
  - re2=2025.11.05=h6b3e72e_0
  - readline=8.3=hc2a1206_0
  - regions=0.11=py314hc02f841_0
  - requests=2.32.5=pyhcf101f3_1
  - s2n=1.5.14=hdbd6064_0
  - sbpy=0.6.0=pyhd8ed1ab_0
  - scikit-image=0.26.0=np2py314hda1ea4c_0
  - scipy=1.16.3=py314hf07bd8e_2
  - secretstorage=3.4.1=py314hdafbbf9_0
  - semantic_version=2.10.0=pyhd8ed1ab_0
  - setuptools=80.9.0=py314h06a4308_0
  - shapely=2.1.2=py314h2748424_0
  - sip=6.12.0=py314h695c4d2_0
  - six=1.17.0=py314h06a4308_0
  - snappy=1.2.2=h4bcf44c_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - soupsieve=2.8.1=pyhd8ed1ab_0
  - spiceypy=8.0.0=py314hc02f841_0
  - spirv-tools=2025.1=hdb19cb5_0
  - sqlite=3.51.1=he0a8d7e_0
  - synphot=1.6.1=py314hc02f841_0
  - tbb=2021.13.0=h8d10470_4
  - tbb-devel=2021.13.0=h74b38a2_4
  - tifffile=2025.10.4=py314h06a4308_0
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.1=py314h5eee18b_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - uriparser=0.9.8=hac33072_0
  - urllib3=2.6.2=pyhd8ed1ab_0
  - utf8proc=2.6.1=h5eee18b_1
  - wayland=1.24.0=hdac8c69_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - werkzeug=3.1.4=pyhcf101f3_0
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xerces-c=3.3.0=ha155076_0
  - xkeyboard-config=2.44=h382ed1a_1
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxrandr=1.5.4=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxshmfence=1.3.3=h9b100fa_0
  - xorg-libxxf86vm=1.1.6=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
prefix: /home/sdg297/miniconda3/envs/lsst
